### ISSUE TITLE
[Todo] Rounded SVG

### ISSUE THREAD

**Issue by zaydek** [feathericons/feathericons.dev#14]
Rounded background SVG feels a little too rounded. Try something less aggressive like 24 or 28 instead of 32.

**Comment by anthonygedeon** [comment]
What SVG's are too rounded?

**Comment by zaydek** [comment]
This one you don’t need to worry about. This has to do with the rounded background effect. I want to experiment with different aspect ratios to see if I can make the rounded effect more pleasant, but this is purely a cosmetic thing.

**Comment by anthonygedeon** [comment]
What issues should I focus on? 

Is there a Figma design available?

**Comment by zaydek** [comment]
There is but it’s not exceptionally well organized: https://www.figma.com/file/O39qXQzsX22O3GRucgKC7d/feathericons.dev.

There aren’t a lot of issues that are easy to delegate just yet. I don’t think you need to worry about submitting PR requests until I work on the site again, which will be soon. I’ll try to follow-up here to let you know when that is.

I really do appreciate your work! Let’s circle back in a few days. 😁
