### ISSUE TITLE
[Todo] Do ‘Follow me!’ instead of ‘Follow on Twitter’

### ISSUE THREAD

**Issue by zaydek** [feathericons/feathericons.dev#15]
Confusing with Twitter logo.

**Comment by anthonygedeon** [comment]
I'll tackle this issue

**Comment by zaydek** [comment]
FWIW I’m working on this project about 1-2 days per week. I think it’s about 60% of the way there, and I expect every 1-2 days I work on it will be like another 15%. With your contributions, we can push this to production sooner!

**Comment by anthonygedeon** [comment]
I usually contribute to open source projects on Tue, Thur, and Sat. I'll try to complete more issues today!

**Comment by zaydek** [comment]
Thank you! That’s very kind of you.
