### ISSUE TITLE
[Todo] Consider darkening the background

### ISSUE THREAD

**Issue by zaydek** [feathericons/feathericons.dev#16]
To better resemble current feathericons.com.

**Comment by anthonygedeon** [comment]
Is this repo currently taking pull requests? I can close some of the available issues if needed!

**Comment by zaydek** [comment]
Absolutely! I can’t guarantee I will accept all of them but you’re more than welcome to contribute.

If you try to build this locally, you’ll need to run `yarn tw-dev` first in order to build Tailwind CSS. Besides that, you should be able to get started!

**Comment by anthonygedeon** [comment]
Thanks, I'll get started then!

**Comment by anthonygedeon** [comment]
Just to clarify, do you mean you want a color that's closer to black? The same black color that feathericon uses? Or just a darker gray color.

**Comment by zaydek** [comment]
This one I’m not 100% sure we need to actually do. I was just recommended it is all. The idea was to make the new site _feel_ more like the whole site but that’s not a huge priority of mine. I think the other issues would be more worthwhile than this one.
